### ISSUE TITLE
Many .fxs files remaining

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/doc#6]
bclaise@new:~$ sudo find / -name *.fxs -print
Shows an interesting output.

**Comment by evyncke** [comment]
Indeed beside the files coming with ConfD, there are files such as:
/var/yang/ietf/YANG/ietf-composed-vpn-svc@2018-08-21.fxs 
Dated from yesterday 00:21 UTC
:-(

**Comment by evyncke** [comment]
There was a bug into YANG-IETF.py stopping the execution of the daily cronjob.
Fixed
